Sbi 17 multi site blog post
spacebetween/spacebetween.github.io pull request #75
Opened 2016-10-27 14:16 UTC by maggyb

2016-10-27 14:31 UTC, lukefrake requested changes
Reeeeally good post Maggy, great work :)

couple of minor points to look at, but really good!

2016-10-27 14:31 UTC, lukefrake commented on _posts/2016-10-27-journal-of-a-junior-multisite.md
> +Hello! Maggy here on my long overdue second blog post in my Journal of a Junior series! This is my sixth month working at Space Between, I have worked on so many projects, with so many amazing techno
One Umbraco CMS _instance_

2016-10-27 14:31 UTC, lukefrake commented on _posts/2016-10-27-journal-of-a-junior-multisite.md
> +Hello! Maggy here on my long overdue second blog post in my Journal of a Junior series! This is my sixth month working at Space Between, I have worked on so many projects, with so many amazing techno
I'd probably link to Umbraco website on this

2016-10-27 14:31 UTC, lukefrake commented on _posts/2016-10-27-journal-of-a-junior-multisite.md
> +###Step 1: Setting up
I would suggest starting at Creating DocTypes and just mention in it that people can see the documentation page for getting started.

This section doesn't really say anything about getting started.

2016-10-27 14:31 UTC, lukefrake commented on _posts/2016-10-27-journal-of-a-junior-multisite.md
> +I've chosen this because it was one of the tasks I thought was going to be very difficult. It involved so many things I'd never encountered before, and was a big learning curve - but very rewarding a
I love this paragraph 😃

2016-10-27 14:31 UTC, lukefrake commented on _posts/2016-10-27-journal-of-a-junior-multisite.md
> +I'm going to be showing the multisite we made for [HRGO Recruitment](http://www.hrgo.co.uk/) in this example. You will want to start with creating some templates for your sites. I personally have use
If I was reading this I'd love to read some example resources.

2016-10-28 10:06 UTC, lukefrake commented on _posts/2016-10-27-journal-of-a-junior-multisite.md
> +###Step 1: Setting up
Step 1 goes to step 3 now.

2016-10-28 10:48 UTC, lukefrake approved these changes

2016-10-28 10:48 UTC, lukefrake commented
👍

2016-10-28 10:49 UTC, merged

2016-10-28 11:25 UTC, f000 commented on _posts/2016-10-27-journal-of-a-junior-multisite.md
> +    string fonts = websiteSettings.GetProperty("fontReference").Value.ToString();
btw I think more elegant style would be websiteSettings.GetPropertyValue<string>("fontReference");

2016-10-28 11:26 UTC, f000 commented on _posts/2016-10-27-journal-of-a-junior-multisite.md
> +{
btw idk if we should present this piece of code... I think it's suboptimal in terms of caching